pool:
  vmImage: macOS-10.15
trigger:
- buildbranch_osx
pr: none
stages:
- stage: stage_0
  jobs:
  - job: stage_0_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-moveit-resources-prbt-pg70-support ros-galactic-moveit-ros-visualization
          ros-galactic-pilz-industrial-motion-planner ros-galactic-moveit-ros
      displayName: Build ros-galactic-moveit-resources-prbt-pg70-support ros-galactic-moveit-ros-visualization
        ros-galactic-pilz-industrial-motion-planner ros-galactic-moveit-ros
- stage: stage_1
  jobs:
  - job: stage_1_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-moveit-planners ros-galactic-moveit
      displayName: Build ros-galactic-moveit-planners ros-galactic-moveit
