pool:
  vmImage: macOS-11
trigger:
- buildbranch_osx_arm64
pr: none
stages:
- stage: stage_0
  jobs:
  - job: stage_0_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-moveit-ros-planning ros-galactic-moveit-plugins
      displayName: Build ros-galactic-moveit-ros-planning ros-galactic-moveit-plugins
- stage: stage_1
  jobs:
  - job: stage_1_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-moveit-kinematics ros-galactic-moveit-ros-warehouse
          ros-galactic-moveit-planners-ompl ros-galactic-moveit-ros-robot-interaction
      displayName: Build ros-galactic-moveit-kinematics ros-galactic-moveit-ros-warehouse
        ros-galactic-moveit-planners-ompl ros-galactic-moveit-ros-robot-interaction
- stage: stage_2
  jobs:
  - job: stage_2_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-moveit-ros-move-group ros-galactic-moveit-ros-benchmarks
          ros-galactic-moveit-resources-prbt-moveit-config ros-galactic-moveit-ros-planning-interface
      displayName: Build ros-galactic-moveit-ros-move-group ros-galactic-moveit-ros-benchmarks
        ros-galactic-moveit-resources-prbt-moveit-config ros-galactic-moveit-ros-planning-interface
- stage: stage_3
  jobs:
  - job: stage_3_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-moveit-resources-prbt-pg70-support ros-galactic-moveit-ros-visualization
          ros-galactic-pilz-industrial-motion-planner ros-galactic-moveit-ros
      displayName: Build ros-galactic-moveit-resources-prbt-pg70-support ros-galactic-moveit-ros-visualization
        ros-galactic-pilz-industrial-motion-planner ros-galactic-moveit-ros
- stage: stage_4
  jobs:
  - job: stage_4_job_0
    steps:
    - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-galactic-moveit-planners ros-galactic-moveit
      displayName: Build ros-galactic-moveit-planners ros-galactic-moveit
