package:
  name: ros-galactic-demo-nodes-py
  version: 0.14.3
source:
  git_url: https://github.com/ros2-gbp/demos-release.git
  git_rev: release/galactic/demo_nodes_py/0.14.3-1
  folder: ros-galactic-demo-nodes-py/src/work
  patches:
    - patch/ros-galactic-demo-nodes-py.patch

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pytest
    - python
    - ros-galactic-ament-copyright
    - ros-galactic-ament-flake8
    - ros-galactic-ament-pep257
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-example-interfaces
    - ros-galactic-rclpy
    - ros-galactic-ros-workspace
    - ros-galactic-std-msgs
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
