package:
  name: ros-galactic-moveit-planners-ompl
  version: 2.3.2
source:
  git_url: https://github.com/moveit/moveit2-release.git
  git_rev: release/galactic/moveit_planners_ompl/2.3.2-2
  folder: ros-galactic-moveit-planners-ompl/src/work
  patches:
    - patch/ros-galactic-moveit-planners-ompl.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - eigen
    - llvm-openmp
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-eigen3-cmake-module
    - ros-galactic-moveit-common
    - ros-galactic-moveit-core
    - ros-galactic-moveit-msgs
    - ros-galactic-moveit-resources-fanuc-moveit-config
    - ros-galactic-moveit-resources-panda-moveit-config
    - ros-galactic-moveit-resources-pr2-description
    - ros-galactic-moveit-ros-planning
    - ros-galactic-ompl
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-tf2-eigen
    - ros-galactic-tf2-ros
    - ros2-distro-mutex 0.1 galactic
  run:
    - llvm-openmp
    - python
    - ros-galactic-moveit-core
    - ros-galactic-moveit-msgs
    - ros-galactic-moveit-ros-planning
    - ros-galactic-ompl
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-ros-workspace
    - ros-galactic-tf2-eigen
    - ros-galactic-tf2-ros
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
