package:
  name: ros-galactic-moveit-ros
  version: 2.3.2
source:
  git_url: https://github.com/moveit/moveit2-release.git
  git_rev: release/galactic/moveit_ros/2.3.2-2
  folder: ros-galactic-moveit-ros/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 3
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-moveit-ros-benchmarks
    - ros-galactic-moveit-ros-move-group
    - ros-galactic-moveit-ros-planning
    - ros-galactic-moveit-ros-planning-interface
    - ros-galactic-moveit-ros-robot-interaction
    - ros-galactic-moveit-ros-visualization
    - ros-galactic-moveit-ros-warehouse
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
